Update Dockerfile

diff --git a/imm/Dockerfile b/imm/Dockerfile
--- a/imm/Dockerfile
+++ b/imm/Dockerfile
@@ -6,15 +6,13 @@ COPY depends.sh .
 RUN bash depends.sh
   
 FROM soft AS git
-WORKDIR /src
 ENV FORCE_UNSAFE_CONFIGURE=1
 COPY buildroot /src/
 COPY make.sh /src/make.sh
 COPY ax6.config /src/ax6.config
 COPY 6088.config /src/6088.config
 RUN bash make.sh
-RUN cp /src/dl/usign* /
-
+RUN if [ $(du -sm /src/dl | awk '{print $1}') -gt 1000 ]; then echo "Size check passed."; else cp /size_check_error /root/ && exit 1; fi
 FROM soft
 COPY --from=git /src /src
 CMD bash
